# Generated by Django 5.1.7 on 2025-10-06 11:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['sale', 'id'], 'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0, help_text='Automatically calculated as 5% of subtotal if delivery is required (in UGX)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='delivery_required',
            field=models.BooleanField(default=False, help_text='Check if customer needs delivery'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (0-99.99)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.PositiveIntegerField(help_text='Price per unit at time of sale (in UGX)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
